defmodule ExPipedrive.ActivityType do
  @moduledoc """
  An activity type in Pipedrive (`/api/v1/activityTypes`).

  `:key_string` is generated by Pipedrive from `:name` on create. Built-in
  types have `:is_custom_flag` false; custom types are created via the API
  (admin scope).
  """

  use TypedStruct
  use ExPipedrive.Structable

  @type key_string :: binary()

  typedstruct do
    field :id, pos_integer()
    field :order_nr, integer()
    field :name, String.t()
    field :key_string, key_string()
    field :icon_key, String.t()
    field :active_flag, boolean(), default: true
    field :color, String.t()
    field :is_custom_flag, boolean(), default: false
    field :add_time, NaiveDateTime.t() | DateTime.t()
    field :update_time, NaiveDateTime.t() | DateTime.t()
    field :original_object, map()
  end

  def handle_transform(map, original) do
    map
    |> Map.update(:add_time, nil, &parse_datetime/1)
    |> Map.update(:update_time, nil, &parse_datetime/1)
    |> Map.put(:original_object, original)
  end
end
